### ISSUE TITLE
signature_invalid

### ISSUE THREAD

**Issue by mkfs** [geoffjentry/ROAuth#2]
Unable to log in via OAuth even though I have a consumer-key, consumer-secret, oauth-key (pregenerated), and oauth-token).

I've been getting 'signature_invalid' when I attempt to connect via ROAuth (after manually setting signMethod='HMAC' and handshakeComplete=TRUE). I successfully connected to the same site using these tokens via Ruby and its 'roauth' gem.

It looks like I'm encountering this issue:
http://lists.hexdump.org/pipermail/twitter-users-hexdump.org/2012-February/000058.html
Judging by the Github timestamps on the repo, this hasn't been fixed yet.

Any chance of an update that works? Or should I just start doing my data downloading in Ruby?

**Comment by geoffjentry** [comment]
Hi there, Duncant Temple Lang took over ROAuth, please look at his fork:
https://github.com/duncantl/ROAuth

Also, if you haven't already, try using the version on my website (built from github):
http://geoffjentry.hexdump.org/ROAuth_0.9.2.zip
or
http://geoffjentry.hexdump.org/ROAuth_0.9.2.tar.gz

**Comment by mkfs** [comment]
OK, I'll bring the issue up there when I have a fix. Tried 0.9.2, an archive of 0.9.0, and the version in ducantl's repo -- no dice. Going to extract the signing methods and try to get them to work like the ruby code.

**Comment by mkfs** [comment]
I added some print() statements into oauthGET() and the OpenAuth header looks fine (key and token are not corrupted, all fields are present). The problem may be in the digest package or RCurl; the AuthError message returned is now 'parameter_rejected, not 'signature_invalid'.

ROAuth is doing its job as far as I can tell, so I'm closing the issue (even though I still can't get it to work on this site).

One feature request: add a debug parameter that allows the user to print the OAuth header and the results of a GET/POST. Makes it much easier to debug connection errors.
